# Generated by Django 3.0.11 on 2021-04-20 03:30

import datetime
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=10, unique=True)),
                ('used', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('student_identity', models.CharField(auto_created=True, max_length=100, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(10)])),
                ('file', models.FileField(blank=True, null=True, upload_to='static/files')),
                ('image', models.ImageField(default='images/default.jpg', null=True, upload_to='static/images/profiles')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_admission', models.DateField(default=datetime.date)),
                ('mobile_number', models.CharField(max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,15}$')])),
                ('symbol_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('temporary_address', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=100)),
                ('is_studying', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeacherIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=10, unique=True)),
                ('used', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(18)])),
                ('file', models.FileField(blank=True, null=True, upload_to='static/files')),
                ('image', models.ImageField(default='images/default.jpg', null=True, upload_to='static/images/profiles')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_joined', models.DateField(auto_now=True)),
                ('mobile_number', models.CharField(max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,15}$')])),
                ('temporary_address', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=100)),
                ('teacher_identification', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('is_teaching', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Teacher',
                'managed': True,
            },
        ),
    ]
