# Generated by Django 3.0.11 on 2021-04-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('sub_title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, default='img_default.jpg', null=True, upload_to='static/images/news')),
                ('video', models.FileField(blank=True, null=True, upload_to='static/videos')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
